### ISSUE TITLE
Spec Is Invalid

### ISSUE THREAD

**Issue by shellscape** [shotstack/oas-api-definition#48]
:wave: Hey there. According to the swagger (OpenAPI v3) [validator](https://validator.swagger.io/), your spec here is invalid. This prevents users from utilizing the swagger _and_ OpenAPI code generation tools against your spec.

**Comment by jeffski** [comment]
@shellscape - This should now be resolved, see #49 and #50. Also added validation to build scripts and re-deployed API docs.

**Comment by shellscape** [comment]
Thanks. Will give this a go tomorrow morning.
